ID: 2025Y-06M-08D-15h57m04s_WSPp
PID: 214878
START_TIME: 2025-06-08 15:57:04.397435
FILE: ./examples/gpac/example__PAC.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/example__PAC_out/RUNNING/2025Y-06M-08D-15h57m04s_WSPp/
REL_SDIR: examples/gpac/example__PAC_out/
ARGS:
    n_perm: 50
EXIT_STATUS: 0
END_TIME: 2025-06-08 15:57:26.205695
RUN_TIME: 00:00:21
