ID: 2025Y-06M-05D-14h37m43s_MAWH
PID: 93531
START_TIME: 2025-06-05 14:37:43.797127
FILE: ./examples/performance/multiple_gpus/comodulogram.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/performance/multiple_gpus/comodulogram_out/RUNNING/2025Y-06M-05D-14h37m43s_MAWH/
REL_SDIR: examples/performance/multiple_gpus/comodulogram_out/
ARGS:
    batch_size: 4
    pha_bands: 20
    amp_bands: 15
    n_perm: 0
EXIT_STATUS: 0
END_TIME: 2025-06-05 14:37:49.042727
RUN_TIME: 00:00:05
