param_name:
    0: batch_size
    1: batch_size
    2: batch_size
    3: n_channels
    4: n_channels
    5: n_channels
    6: seq_sec
    7: seq_sec
    8: fs
    9: fs
    10: pha_n_bands
    11: pha_n_bands
    12: amp_n_bands
    13: amp_n_bands
    14: n_perm
    15: n_perm
    16: n_perm
    17: fp16
    18: fp16
    19: multi_gpu
param_value:
    0: 1
    1: 4
    2: 16
    3: 1
    4: 4
    5: 16
    6: 1.0
    7: 4.0
    8: 250
    9: 1000
    10: 5
    11: 15
    12: 5
    13: 15
    14: 0
    15: 50
    16: 200
    17: false
    18: true
    19: false
gpac_time_mean:
    0: .nan
    1: .nan
    2: .nan
    3: .nan
    4: .nan
    5: .nan
    6: .nan
    7: .nan
    8: .nan
    9: .nan
    10: .nan
    11: .nan
    12: .nan
    13: .nan
    14: .nan
    15: .nan
    16: .nan
    17: .nan
    18: .nan
    19: .nan
gpac_time_std:
    0: .nan
    1: .nan
    2: .nan
    3: .nan
    4: .nan
    5: .nan
    6: .nan
    7: .nan
    8: .nan
    9: .nan
    10: .nan
    11: .nan
    12: .nan
    13: .nan
    14: .nan
    15: .nan
    16: .nan
    17: .nan
    18: .nan
    19: .nan
tensorpac_time_mean:
    0: 0.049306631088256836
    1: 0.15513229370117188
    2: 0.6093730926513672
    3: 0.03109908103942871
    4: 0.0831913948059082
    5: 0.29050278663635254
    6: 0.04974937438964844
    7: 0.15379667282104492
    8: 0.14795207977294922
    9: 0.8137905597686768
    10: 0.09839177131652832
    11: 0.20700502395629883
    12: 0.08020758628845215
    13: 0.14720535278320312
    14: 0.14825749397277832
    15: 0.14797043800354004
    16: 0.15338850021362305
    17: 0.1514909267425537
    18: .nan
    19: 0.14999747276306152
tensorpac_time_std:
    0: 0.0
    1: 0.0
    2: 0.0
    3: 0.0
    4: 0.0
    5: 0.0
    6: 0.0
    7: 0.0
    8: 0.0
    9: 0.0
    10: 0.0
    11: 0.0
    12: 0.0
    13: 0.0
    14: 0.0
    15: 0.0
    16: 0.0
    17: 0.0
    18: .nan
    19: 0.0
speedup:
    0: .nan
    1: .nan
    2: .nan
    3: .nan
    4: .nan
    5: .nan
    6: .nan
    7: .nan
    8: .nan
    9: .nan
    10: .nan
    11: .nan
    12: .nan
    13: .nan
    14: .nan
    15: .nan
    16: .nan
    17: .nan
    18: .nan
    19: .nan
config:
    0:
        batch_size: 1
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    1:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    2:
        batch_size: 16
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    3:
        batch_size: 4
        n_channels: 1
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    4:
        batch_size: 4
        n_channels: 4
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    5:
        batch_size: 4
        n_channels: 16
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    6:
        batch_size: 4
        n_channels: 8
        seq_sec: 1.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    7:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    8:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    9:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 1000
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    10:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 5
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    11:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 15
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    12:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 5
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    13:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    14:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    15:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 50
        fp16: false
        multi_gpu: false
        device: cuda
    16:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 200
        fp16: false
        multi_gpu: false
        device: cuda
    17:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    18:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: true
        multi_gpu: false
        device: cuda
    19:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
gpac_throughput:
    0: .nan
    1: .nan
    2: .nan
    3: .nan
    4: .nan
    5: .nan
    6: .nan
    7: .nan
    8: .nan
    9: .nan
    10: .nan
    11: .nan
    12: .nan
    13: .nan
    14: .nan
    15: .nan
    16: .nan
    17: .nan
    18: .nan
    19: .nan
