ID: 2025Y-06M-08D-13h27m36s_V57T
PID: 302884
START_TIME: 2025-06-08 13:27:36.531869
FILE: ./examples/gpac/example__PAC.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/example__PAC_out/RUNNING/2025Y-06M-08D-13h27m36s_V57T/
REL_SDIR: examples/gpac/example__PAC_out/
ARGS:
    n_perm: 50
    batch_size: 2
EXIT_STATUS: 0
END_TIME: 2025-06-08 13:27:57.687043
RUN_TIME: 00:00:21
