ID: 2025Y-06M-09D-23h59m20s_tfUr
PID: 203159
START_TIME: 2025-06-09 23:59:20.785748
FILE: 
    /home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/_parameter_sweep_helper_visualize.py
SDIR: 
    /home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/_parameter_sweep_helper_visualize_out/RUNNING/2025Y-06M-09D-23h59m20s_tfUr/
REL_SDIR: 
    ../../../../../../home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/_parameter_sweep_helper_visualize_out/
ARGS: {}
EXIT_STATUS: 0
END_TIME: 2025-06-09 23:59:34.843361
RUN_TIME: 00:00:14
