ID: 2025Y-06M-09D-13h40m26s_XK9R
PID: 203085
START_TIME: 2025-06-09 13:40:26.790471
FILE: 
    /home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/parameter_sweep_benchmark.py
SDIR: 
    /home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/parameter_sweep_benchmark_out/RUNNING/2025Y-06M-09D-13h40m26s_XK9R/
REL_SDIR: 
    ../../../../../../home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/parameter_sweep_benchmark_out/
ARGS:
    no_quick: false
    quick: true
EXIT_STATUS: 0
END_TIME: 2025-06-09 13:40:28.829882
RUN_TIME: 00:00:02
