ID: 2025Y-06M-05D-14h37m23s_7gsL
PID: 92829
START_TIME: 2025-06-05 14:37:23.559970
FILE: ./examples/performance/multiple_gpus/vram.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/performance/multiple_gpus/vram_out/RUNNING/2025Y-06M-05D-14h37m23s_7gsL/
REL_SDIR: examples/performance/multiple_gpus/vram_out/
ARGS:
    n_perm: 0
EXIT_STATUS: 1
END_TIME: 2025-06-05 14:37:25.785275
RUN_TIME: 00:00:02
