ID: 2025Y-06M-09D-19h18m52s_OOyf
PID: 111265
START_TIME: 2025-06-09 19:18:52.887471
FILE: 
    /home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/parameter_sweep_benchmark.py
SDIR: 
    /home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/parameter_sweep_benchmark_out/RUNNING/2025Y-06M-09D-19h18m52s_OOyf/
REL_SDIR: 
    ../../../../../../home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/parameter_sweep_benchmark_out/
ARGS:
    no_quick: false
    shuffle: false
    quick: true
EXIT_STATUS: 0
END_TIME: 2025-06-09 20:49:47.886333
RUN_TIME: 01:30:54
