ID: 2025Y-06M-08D-13h32m47s_YPPs
PID: 8875
START_TIME: 2025-06-08 13:32:47.968310
FILE: ./examples/gpac/example__PAC.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/example__PAC_out/RUNNING/2025Y-06M-08D-13h32m47s_YPPs/
REL_SDIR: examples/gpac/example__PAC_out/
ARGS:
    n_perm: 50
    batch_size: 2
EXIT_STATUS: 0
END_TIME: 2025-06-08 13:33:11.642628
RUN_TIME: 00:00:23
