ID: 2025Y-06M-05D-17h13m16s_tkvX
PID: 155773
START_TIME: 2025-06-05 17:13:16.603725
FILE: ./examples/performance/comprehensive_benchmark.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/performance/comprehensive_benchmark_out/RUNNING/2025Y-06M-05D-17h13m16s_tkvX/
REL_SDIR: examples/performance/comprehensive_benchmark_out/
ARGS:
    n_repeats: 3
EXIT_STATUS: 0
END_TIME: 2025-06-05 17:13:22.909550
RUN_TIME: 00:00:06
