ID: 2025Y-06M-08D-11h10m01s_oFHZ
PID: 99674
START_TIME: 2025-06-08 11:10:01.361286
FILE: ./examples/gpac/core/example__ModulationIndex.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/core/example__ModulationIndex_out/RUNNING/2025Y-06M-08D-11h10m01s_oFHZ/
REL_SDIR: examples/gpac/core/example__ModulationIndex_out/
ARGS:
    n_bins: 18
    temperature: 0.01
EXIT_STATUS: 0
END_TIME: 2025-06-08 11:10:06.833820
RUN_TIME: 00:00:05
