ID: 2025Y-06M-09D-23h53m50s_QB67
PID: 195782
START_TIME: 2025-06-09 23:53:50.013059
FILE: 
    /home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/_parameter_sweep_helper_visualize.py
SDIR: 
    /home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/_parameter_sweep_helper_visualize_out/RUNNING/2025Y-06M-09D-23h53m50s_QB67/
REL_SDIR: 
    ../../../../../../home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/_parameter_sweep_helper_visualize_out/
ARGS: {}
EXIT_STATUS: 0
END_TIME: 2025-06-09 23:54:04.690331
RUN_TIME: 00:00:14
