ID: 2025Y-06M-08D-12h59m27s_3GZz
PID: 262223
START_TIME: 2025-06-08 12:59:27.345915
FILE: ./examples/gpac/example__PAC.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/example__PAC_out/RUNNING/2025Y-06M-08D-12h59m27s_3GZz/
REL_SDIR: examples/gpac/example__PAC_out/
ARGS:
    n_perm: 50
    batch_size: 2
EXIT_STATUS: 0
END_TIME: 2025-06-08 12:59:41.785430
RUN_TIME: 00:00:14
