ID: 2025Y-06M-08D-13h21m48s_Lj0D
PID: 295077
START_TIME: 2025-06-08 13:21:48.142012
FILE: ./examples/gpac/example__PAC.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/example__PAC_out/RUNNING/2025Y-06M-08D-13h21m48s_Lj0D/
REL_SDIR: examples/gpac/example__PAC_out/
ARGS:
    n_perm: 50
    batch_size: 2
EXIT_STATUS: 0
END_TIME: 2025-06-08 13:22:09.025174
RUN_TIME: 00:00:20
