ID: 2025Y-06M-08D-12h57m11s_J2yX
PID: 259013
START_TIME: 2025-06-08 12:57:11.786860
FILE: ./examples/gpac/example__PAC.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/example__PAC_out/RUNNING/2025Y-06M-08D-12h57m11s_J2yX/
REL_SDIR: examples/gpac/example__PAC_out/
ARGS:
    n_perm: 50
    batch_size: 2
EXIT_STATUS: 0
END_TIME: 2025-06-08 12:57:24.463902
RUN_TIME: 00:00:12
