ID: 2025Y-06M-08D-14h26m33s_ah48
PID: 87080
START_TIME: 2025-06-08 14:26:33.157823
FILE: ./examples/gpac/example__PAC.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/example__PAC_out/RUNNING/2025Y-06M-08D-14h26m33s_ah48/
REL_SDIR: examples/gpac/example__PAC_out/
ARGS:
    n_perm: 50
    batch_size: 2
EXIT_STATUS: 0
END_TIME: 2025-06-08 14:27:15.559114
RUN_TIME: 00:00:42
