ID: 2025Y-06M-08D-10h43m27s_MqXV
PID: 61850
START_TIME: 2025-06-08 10:43:27.834862
FILE: ./examples/gpac/core/example__ModulationIndex.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/core/example__ModulationIndex_out/RUNNING/2025Y-06M-08D-10h43m27s_MqXV/
REL_SDIR: examples/gpac/core/example__ModulationIndex_out/
ARGS:
    n_bins: 18
    temperature: 0.01
EXIT_STATUS: 0
END_TIME: 2025-06-08 10:43:33.314256
RUN_TIME: 00:00:05
