ID: 2025Y-06M-09D-22h38m40s_oywR
PID: 91007
START_TIME: 2025-06-09 22:38:40.440826
FILE: 
    /home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/_parameter_sweep_helper_visualize.py
SDIR: 
    /home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/_parameter_sweep_helper_visualize_out/RUNNING/2025Y-06M-09D-22h38m40s_oywR/
REL_SDIR: 
    ../../../../../../home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/_parameter_sweep_helper_visualize_out/
ARGS: {}
EXIT_STATUS: 0
END_TIME: 2025-06-09 22:38:50.537187
RUN_TIME: 00:00:10
