ID: 2025Y-06M-09D-22h02m22s_jCMm
PID: 41283
START_TIME: 2025-06-09 22:02:22.925958
FILE: 
    /home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/_parameter_sweep_helper_visualize.py
SDIR: 
    /home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/_parameter_sweep_helper_visualize_out/RUNNING/2025Y-06M-09D-22h02m22s_jCMm/
REL_SDIR: 
    ../../../../../../home/ywatanabe/proj/gPAC/examples/benchmark/parameter_sweep/_parameter_sweep_helper_visualize_out/
ARGS: {}
EXIT_STATUS: 0
END_TIME: 2025-06-09 22:02:40.328722
RUN_TIME: 00:00:17
