param_name:
    0: batch_size
    1: batch_size
    2: batch_size
    3: batch_size
    4: batch_size
    5: n_channels
    6: n_channels
    7: n_channels
    8: n_channels
    9: n_channels
    10: seq_sec
    11: seq_sec
    12: seq_sec
    13: seq_sec
    14: fs
    15: fs
    16: fs
    17: pha_n_bands
    18: pha_n_bands
    19: pha_n_bands
    20: pha_n_bands
    21: amp_n_bands
    22: amp_n_bands
    23: amp_n_bands
    24: amp_n_bands
    25: n_perm
    26: n_perm
    27: n_perm
    28: n_perm
    29: n_perm
    30: fp16
    31: fp16
    32: multi_gpu
    33: multi_gpu
param_value:
    0: 1
    1: 2
    2: 4
    3: 8
    4: 16
    5: 1
    6: 2
    7: 4
    8: 8
    9: 16
    10: 1.0
    11: 2.0
    12: 4.0
    13: 8.0
    14: 250
    15: 500
    16: 1000
    17: 5
    18: 10
    19: 15
    20: 20
    21: 5
    22: 10
    23: 15
    24: 20
    25: 0
    26: 16
    27: 50
    28: 100
    29: 200
    30: false
    31: true
    32: false
    33: true
gpac_time_mean:
    0: .nan
    1: .nan
    2: .nan
    3: .nan
    4: .nan
    5: .nan
    6: .nan
    7: .nan
    8: .nan
    9: .nan
    10: .nan
    11: .nan
    12: .nan
    13: .nan
    14: .nan
    15: .nan
    16: .nan
    17: .nan
    18: .nan
    19: .nan
    20: .nan
    21: .nan
    22: .nan
    23: .nan
    24: .nan
    25: .nan
    26: .nan
    27: .nan
    28: .nan
    29: .nan
    30: .nan
    31: .nan
    32: .nan
    33: .nan
gpac_time_std:
    0: .nan
    1: .nan
    2: .nan
    3: .nan
    4: .nan
    5: .nan
    6: .nan
    7: .nan
    8: .nan
    9: .nan
    10: .nan
    11: .nan
    12: .nan
    13: .nan
    14: .nan
    15: .nan
    16: .nan
    17: .nan
    18: .nan
    19: .nan
    20: .nan
    21: .nan
    22: .nan
    23: .nan
    24: .nan
    25: .nan
    26: .nan
    27: .nan
    28: .nan
    29: .nan
    30: .nan
    31: .nan
    32: .nan
    33: .nan
tensorpac_time_mean:
    0: 0.04960823059082031
    1: 0.08172607421875
    2: 0.15554523468017578
    3: 0.29657697677612305
    4: 0.5945661067962646
    5: 0.03153276443481445
    6: 0.04705977439880371
    7: 0.08144998550415039
    8: 0.15162396430969238
    9: 0.29042530059814453
    10: 0.05057835578918457
    11: 0.08241009712219238
    12: 0.15093326568603516
    13: 0.2821381092071533
    14: 0.15616917610168457
    15: 0.32613611221313477
    16: 0.8278563022613525
    17: 0.09739232063293457
    18: 0.14813590049743652
    19: 0.2086498737335205
    20: 0.2626626491546631
    21: 0.08003544807434082
    22: 0.11265850067138672
    23: 0.1480398178100586
    24: 0.18137454986572266
    25: 0.14799737930297852
    26: 0.14786696434020996
    27: 0.14821553230285645
    28: 0.14873886108398438
    29: 0.15079641342163086
    30: 0.14790964126586914
    31: .nan
    32: 0.14980387687683105
    33: .nan
tensorpac_time_std:
    0: 0.0
    1: 0.0
    2: 0.0
    3: 0.0
    4: 0.0
    5: 0.0
    6: 0.0
    7: 0.0
    8: 0.0
    9: 0.0
    10: 0.0
    11: 0.0
    12: 0.0
    13: 0.0
    14: 0.0
    15: 0.0
    16: 0.0
    17: 0.0
    18: 0.0
    19: 0.0
    20: 0.0
    21: 0.0
    22: 0.0
    23: 0.0
    24: 0.0
    25: 0.0
    26: 0.0
    27: 0.0
    28: 0.0
    29: 0.0
    30: 0.0
    31: .nan
    32: 0.0
    33: .nan
speedup:
    0: .nan
    1: .nan
    2: .nan
    3: .nan
    4: .nan
    5: .nan
    6: .nan
    7: .nan
    8: .nan
    9: .nan
    10: .nan
    11: .nan
    12: .nan
    13: .nan
    14: .nan
    15: .nan
    16: .nan
    17: .nan
    18: .nan
    19: .nan
    20: .nan
    21: .nan
    22: .nan
    23: .nan
    24: .nan
    25: .nan
    26: .nan
    27: .nan
    28: .nan
    29: .nan
    30: .nan
    31: .nan
    32: .nan
    33: .nan
config:
    0:
        batch_size: 1
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    1:
        batch_size: 2
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    2:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    3:
        batch_size: 8
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    4:
        batch_size: 16
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    5:
        batch_size: 4
        n_channels: 1
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    6:
        batch_size: 4
        n_channels: 2
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    7:
        batch_size: 4
        n_channels: 4
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    8:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    9:
        batch_size: 4
        n_channels: 16
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    10:
        batch_size: 4
        n_channels: 8
        seq_sec: 1.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    11:
        batch_size: 4
        n_channels: 8
        seq_sec: 2.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    12:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    13:
        batch_size: 4
        n_channels: 8
        seq_sec: 8.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    14:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    15:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 500
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    16:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 1000
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    17:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 5
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    18:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    19:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 15
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    20:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 20
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    21:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 5
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    22:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 10
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    23:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    24:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 20
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    25:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    26:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 16
        fp16: false
        multi_gpu: false
        device: cuda
    27:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 50
        fp16: false
        multi_gpu: false
        device: cuda
    28:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 100
        fp16: false
        multi_gpu: false
        device: cuda
    29:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 200
        fp16: false
        multi_gpu: false
        device: cuda
    30:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    31:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: true
        multi_gpu: false
        device: cuda
    32:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: false
        device: cuda
    33:
        batch_size: 4
        n_channels: 8
        seq_sec: 4.0
        fs: 250
        pha_n_bands: 10
        amp_n_bands: 15
        n_perm: 0
        fp16: false
        multi_gpu: true
        device: cuda
gpac_throughput:
    0: .nan
    1: .nan
    2: .nan
    3: .nan
    4: .nan
    5: .nan
    6: .nan
    7: .nan
    8: .nan
    9: .nan
    10: .nan
    11: .nan
    12: .nan
    13: .nan
    14: .nan
    15: .nan
    16: .nan
    17: .nan
    18: .nan
    19: .nan
    20: .nan
    21: .nan
    22: .nan
    23: .nan
    24: .nan
    25: .nan
    26: .nan
    27: .nan
    28: .nan
    29: .nan
    30: .nan
    31: .nan
    32: .nan
    33: .nan
