ID: 2025Y-06M-08D-15h46m56s_Vp7u
PID: 200405
START_TIME: 2025-06-08 15:46:56.855216
FILE: ./examples/gpac/example__PAC.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/example__PAC_out/RUNNING/2025Y-06M-08D-15h46m56s_Vp7u/
REL_SDIR: examples/gpac/example__PAC_out/
ARGS:
    n_perm: 50
    batch_size: 2
EXIT_STATUS: 0
END_TIME: 2025-06-08 15:47:10.262795
RUN_TIME: 00:00:13
