ID: 2025Y-06M-09D-00h44m35s_OgLV
PID: 38442
START_TIME: 2025-06-09 00:44:35.688241
FILE: ./examples/gpac/example__Hilbert.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/example__Hilbert_out/RUNNING/2025Y-06M-09D-00h44m35s_OgLV/
REL_SDIR: examples/gpac/example__Hilbert_out/
ARGS:
    sample_rate: 1000.0
    duration: 2.0
EXIT_STATUS: 0
END_TIME: 2025-06-09 00:44:40.287789
RUN_TIME: 00:00:04
