ID: 2025Y-06M-05D-20h46m44s_A0xq
PID: 292212
START_TIME: 2025-06-05 20:46:44.262701
FILE: ./examples/performance/ultra_speed_benchmark.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/performance/ultra_speed_benchmark_out/RUNNING/2025Y-06M-05D-20h46m44s_A0xq/
REL_SDIR: examples/performance/ultra_speed_benchmark_out/
ARGS: {}
EXIT_STATUS: 0
END_TIME: 2025-06-05 20:51:27.916244
RUN_TIME: 00:04:43
