ID: 2025Y-06M-08D-10h51m30s_EOSL
PID: 73164
START_TIME: 2025-06-08 10:51:30.378990
FILE: ./examples/gpac/core/example__ModulationIndex.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/core/example__ModulationIndex_out/RUNNING/2025Y-06M-08D-10h51m30s_EOSL/
REL_SDIR: examples/gpac/core/example__ModulationIndex_out/
ARGS:
    n_bins: 18
    temperature: 0.01
EXIT_STATUS: 0
END_TIME: 2025-06-08 10:51:35.882389
RUN_TIME: 00:00:05
