ID: 2025Y-06M-08D-11h05m22s_AcjI
PID: 93597
START_TIME: 2025-06-08 11:05:22.934375
FILE: ./examples/gpac/core/example__ModulationIndex.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/core/example__ModulationIndex_out/RUNNING/2025Y-06M-08D-11h05m22s_AcjI/
REL_SDIR: examples/gpac/core/example__ModulationIndex_out/
ARGS:
    n_bins: 18
    temperature: 0.01
EXIT_STATUS: 0
END_TIME: 2025-06-08 11:05:28.471178
RUN_TIME: 00:00:05
