ID: 2025Y-06M-08D-10h48m20s_l7r5
PID: 68675
START_TIME: 2025-06-08 10:48:20.796677
FILE: ./examples/gpac/core/example__ModulationIndex.py
SDIR: 
    /data/gpfs/projects/punim2354/ywatanabe/gPAC/examples/gpac/core/example__ModulationIndex_out/RUNNING/2025Y-06M-08D-10h48m20s_l7r5/
REL_SDIR: examples/gpac/core/example__ModulationIndex_out/
ARGS:
    n_bins: 18
    temperature: 0.01
EXIT_STATUS: 0
END_TIME: 2025-06-08 10:48:26.261304
RUN_TIME: 00:00:05
